### PR TITLE
Clicked app in tasks highlighted - fix

### PR DESCRIPTION
**Pull request by thewaiter**

### CODE REVIEW

**Comment by avDuma** [comment]
I am not a super fan of fixed color on themes, I prefer to kkep them as variables with color_class and #define .
Why we have modified that line?

(by the way, sorry if I'm disappeared. Lots of work and other project take me away for long time...)

**Comment by thewaiter** [comment]
Hello Alberto. I am glad you are back.

I modified that line because it was a request of one user who was right. See the post #11 here
http://forums.bodhilinux.com/index.php?/topic/13179-feature-requests/

There is a lack of feature when  in the task is more the same apps and user click on the one of them . We simply do not know which app is selected. If you feel I haven't chosen a suitable color, feel free to change it to defined one. Maybe prelight color would be better. Anyway try to keep the idea of solving this issue...

Stefan

**Comment by avDuma** [comment]
Ok, I've seen the bug / lack of feature.
The plain gray solution (191 191 191) you have proposed is good if the shelf base color is a plain gray (with "plain gray" I mean something with RGB channels all with the same value).
Original shelf base color on Radiance has red channel value higher than other (223 215 207), so, if you are ok with it, I propose something could look better for all shelf base color combination:

http://www.enlightenment.org/ss/e-57961436a9fa53.46867709.jpg

mainly the square around clicked apps is bonded to the "master select color", the color described by the "focus" color class.
If you are ok with this proposal, I'll push on github :)

**Comment by JeffHoogland** [comment]
That change looks great.

**Comment by thewaiter** [comment]
I just respected the default bodhi icon set which is gray. I am not sure how it will look with that redish color. I have to try.

**Comment by thewaiter** [comment]
OK, this is my commit
http://i.imgur.com/tncw5xq.png

and this is result of yours:
http://i.imgur.com/hfYjQHO.png

I see something blueish in that. I have no the same color as you have...

**Comment by avDuma** [comment]
The blue comes from the color class "focus". We just have to decide if we want to bond with it or keep a plain gray. 

Il 25 luglio 2016 21:39:59 CEST, thewaiter notifications@github.com ha scritto:

**Comment by thewaiter** [comment]
If you are a theme author, it should be up to you :)

**Comment by JeffHoogland** [comment]
I like it changing with the theme color personally. Both seem fine though.

**Pull request merged**
